a=int(input("enter 1st number     "))
b=int(input("enter 2nd number     "))
c=int(input("enter 3rd number     "))
d=int(input("enter 4th number     "))
f=int(input("enter 5th number     "))
g=int(input("enter 6th number     "))
h=int(input("enter 7th number     "))
i=int(input("enter 8th number     "))

myset=set()
myset.add(a)
myset.add(b)
myset.add(c)
myset.add(d)
myset.add(f)
myset.add(g)
myset.add(h)
myset.add(i)
print(myset)

